### AUTH HEALTH
GET http://localhost:8000/auth/health 
content-type: application/json

### CREATE USER
POST http://localhost:8000/auth/signup
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "12345678"
}

### LOGIN
POST http://localhost:8000/auth/login
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "12345678"
}

### GET USER
GET http://localhost:8000/api/v1/users/user
content-type: application/json