// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type TbUser struct {
	ID          uuid.UUID
	Email       string
	Password    string
	IsActive    sql.NullBool
	IsSuperuser sql.NullBool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type TbUserProfile struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SteamUser sql.NullString
	GogUser   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
